### ISSUE TITLE
Skip downloaded files?

### ISSUE THREAD

**Issue by HydroHydro** [Xealeph/Yiff.party-Image-Scraper#12]
First of all, thank you for making this! It works really well!

Is it possible that you could make it detect if you already downloaded a file and only get the newest/missing posts?

Thanks!

**Comment by Ruthalas** [comment]
Hey HydroHydro, I am currently working on this exact issue.
I should have a pull-request in to make the update soon.

**Comment by Xealeph** [comment]
Sorry for the delay!
