### ISSUE TITLE
Missing Files On Fantia

### ISSUE THREAD

**Issue by HydroHydro** [Xealeph/Yiff.party-Image-Scraper#16]
It seems that the Fantia downloader has a small issue.

Example:
(NSFW)
https://yiff.party/fantia/21000

This will only download 40 pictures. I didn't count them individually on the website, but that seems to be correct. But the **videos** don't download.

Video example:
(NSFW)
https://yiff.party/fantia/posts/213520

**Comment by Xealeph** [comment]
Thanks! I'll look into it.

**Comment by Xealeph** [comment]
Should work now (I think).
If it does, feel free to close the issue.

**Comment by HydroHydro** [comment]
Looks like that worked! Thank you! :)
