### ISSUE TITLE
Folder Naming Suggestion

### ISSUE THREAD

**Issue by HydroHydro** [Xealeph/Yiff.party-Image-Scraper#18]
Right now, the created folders are simply named with their user number. It can get very confusing to find content when everything is just numbers. I suggest adding the Patreon/Fantia username to the folder name.

One potential issue to this is that previous downloaded folders would have to be renamed. Otherwise the scraper would just make another folder and start downloading everything again.

**Comment by Xealeph** [comment]
I updated the main script with the requested feature.
I also added another script, which renames the already existing folders with the corresponding author name.
Hope this helps.
