### ISSUE TITLE
Second page bug

### ISSUE THREAD

**Issue by viktor02** [Xealeph/Yiff.party-Image-Scraper#2]
If the author has a second page, then the scraper does not download it, can you fix this bug?

**Comment by Xealeph** [comment]
working on it

**Comment by Xealeph** [comment]
i think i got it
if it works, please reply in this thread, so i can close the issue

**Comment by viktor02** [comment]
Hmm...No, i think it doesnt work. 
There is also a new bug with incorrect names. Pictures has names from other posts.

**Comment by Xealeph** [comment]
i'll look into it

**Comment by Xealeph** [comment]
I hope I got everything this time.
Tell me, if there are still things that need fixing.

**Comment by viktor02** [comment]
I don’t have the opportunity to check everything now, I remember about the bug, which means that the program did not print a download message sequentially with each file, but output it all at once at the end before finishing message.

**Comment by Xealeph** [comment]
I think, this bug should be fixed by now (or should at least send some additional info, that the url has been skipped).

You can take your time if you want, as you are (as far as I can see) the only person having a problem with it.
