### ISSUE TITLE
NoneType object is not subscriptable

### ISSUE THREAD

**Issue by HydroHydro** [Xealeph/Yiff.party-Image-Scraper#22]
Found another bug!

Tried to get this URL: https://yiff.party/fantia/4284

And got:
 `Traceback (most recent call last):`
`  File "yiff_image_scraper.py", line 490, in <module>`
`    downloadImages(url, urlCounter, useFolders)`
`  File "yiff_image_scraper.py", line 292, in downloadImages`
`    linkList += fantiaSubroutine(fantiaList)`
`  File "yiff_image_scraper.py", line 197, in fantiaSubroutine`
`    linklist.append(var.a['href'])`
`TypeError: 'NoneType' object is not subscriptable`

**Comment by Xealeph** [comment]
Sure. I'll look into it.

**Comment by Xealeph** [comment]
Well, that was stupidly easy to fix.
I'm very sorry that this took so long.
