### ISSUE TITLE
Download folder messed up on Linux

### ISSUE THREAD

**Issue by sideloading** [Xealeph/Yiff.party-Image-Scraper#4]
The folder creation for .\\Images\\ is broken for Linux, and instead creates hidden files with the path as the filename.

```bash
$ ls -a
.\Images\
.\Images\17697790\
.\Images\17697790\0 0084A251-4A39-4E2E-9AB4-2C5EE2C84688.jpg
.\Images\17697790\001A931F-808A-4B63-9E57-C2AD695FA38F.JPEG
.\Images\17697790\0084A251-4A39-4E2E-9AB4-2C5EE2C84688.jpg
...
```

I'm running Linux (Ubuntu 16.04), Python 3.7.3

```
>>> os.path.abspath(".\\Images\\")
'/home1/bpo5r5/scraper/Yiff.party-Image-Scraper/.\\Images\\'
```

edit: i believe `os.getcwd()` can solve this issue

**Comment by Xealeph** [comment]
Should work properly now.
Thanks for pointing it out!
If it works, please close the issue.

**Comment by sideloading** [comment]
Thanks for the quick fix!
