### ISSUE TITLE
identicals files name erased

### ISSUE THREAD

**Issue by lestrot** [Xealeph/Yiff.party-Image-Scraper#5]
When downloading, files with the same name are erased and only the last seem to be kept, is there a way to fix this? a lot of content can easily disapears.

Do you have any idea how to fix this?

**Comment by Xealeph** [comment]
This is a very crude fix, but i hope it helps.
(It now attaches a number to every picture to separate them and avoid a loss of files)

[yiff_image_scraper_with_counter.zip](https://github.com/Xealeph/Yiff.party-Image-Scraper/files/3925696/yiff_image_scraper_with_counter.zip)
