### ISSUE TITLE
Makes duplicates

### ISSUE THREAD

**Issue by viktor02** [Xealeph/Yiff.party-Image-Scraper#6]
The script makes duplicates, usually they are located nearby, with the same names (except for the number). Perhaps this is due to the download of the attached files and cover art.

**Comment by Xealeph** [comment]
I added an additional script, which should fit your needs (as long as the files are exactly the same (excluding the filename)).
Hope this helps.

**Comment by Xealeph** [comment]
If you're still facing problems, feel free to open up issue again.
