### ISSUE TITLE
Download stops half way

### ISSUE THREAD

**Issue by Behem07h** [Xealeph/Yiff.party-Image-Scraper#7]
When downloading images, download stops half way, giving the error:
Could not find Images. The cause might be a invalid url or there just aren't any Images
Skipping url: https://yiff.party/patreon/103382

I started the downloader with the command 
"python yiff_image_scraper.py https://yiff.party/patreon/103382", and it downloaded about 1.2k images before stopping and giving that error.

I am using python 3.5

**Comment by Xealeph** [comment]
Thank you for notifying me.
I will check it out and see what I can do.

**Comment by Xealeph** [comment]
I actually don't know what causes this (maybe it is the server stopping to take requests), but I added a new feature so you can start the scraper at a custom page number.

Example for page 28 to 30: python yiff_ image_scraper.py 28 30 https://yiff.party/patreon/42

Additionally, the script creates a file for all skipped links.

I know it doesn't fix the issue, but I still hope it helps.

**Comment by Behem07h** [comment]
Thanks!
Actually, since i encountered that error, i've tried running the scraper a
second time and this time it ran till completion. It might be an error on
the server side, or something to do with my internet connection maybe

**Comment by Xealeph** [comment]
Nice to hear that it works for you :)
If you still have troubles (because I didn't test out the new script to its fullest), feel free to open up this issue again.
